version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: glimpse-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: .  # Use current directory where Dockerfile is located
      dockerfile: dockerfile
    container_name: glimpse-backend
    ports:
      - "8000:8000"  # Map port 8000 on container to port 8000 on host
    volumes:
      - .:/app  # Mount current directory into /app inside container
    env_file:
      - .env  # Load environment variables from .env file
    depends_on:
      - redis  # Ensure Redis starts before backend service
    command: uvicorn application:app --host 0.0.0.0 --port 8000  # Start FastAPI app

volumes:
  redis_data:  # Named volume for Redis data persistence
